### ISSUE TITLE
ForRootAsync with contextName not available in MikroOrmModule context 

### ISSUE THREAD

**Issue by occhiojoe** [mikro-orm/nestjs#108]
**Describe the bug**
Hello! I am trying to use two databases connections with this package.  One connection is for MongoDB, the other, Postgres. Unfortunately I can't seem to get beyond initial setup and think I've hit a bug. All I have is a User entity defined for my postgres DB. Nest cannot resolve the dependencies of UserRepository_postgres.  I've tried many things to get this to resolve, so my example below might not be perfect. Hope I am just doing something wrong. Thanks. 

**Stack trace**
```
api              | [10:57:23 PM] Found 0 errors. Watching for file changes.
api              | 
api              | [Nest] 754  - 03/07/2023, 10:57:23 PM     LOG [NestFactory] Starting Nest application...
api              | [Nest] 754  - 03/07/2023, 10:57:23 PM     LOG [InstanceLoader] MikroOrmModule dependencies initialized +98ms
api              | [Nest] 754  - 03/07/2023, 10:57:23 PM     LOG [InstanceLoader] MikroOrmModule dependencies initialized +0ms
api              | [Nest] 754  - 03/07/2023, 10:57:23 PM     LOG [InstanceLoader] MikroOrmMiddlewareModule dependencies initialized +0ms
api              | [Nest] 754  - 03/07/2023, 10:57:23 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the UserRepository_postgres (?). Please make sure that the argument postgres_EntityManager at index [0] is available in the MikroOrmModule context.
api              | 
api              | Potential solutions:
api              | - Is MikroOrmModule a valid NestJS module?
api              | - If postgres_EntityManager is a provider, is it part of the current MikroOrmModule?
api              | - If postgres_EntityManager is exported from a separate @Module, is that module imported within MikroOrmModule?
api              |   @Module({
api              |     imports: [ /* the Module containing postgres_EntityManager */ ]
api              |   })
api              | 
api              | Error: Nest can't resolve dependencies of the UserRepository_postgres (?). Please make sure that the argument postgres_EntityManager at index [0] is available in the MikroOrmModule context.
api              | 
api              | Potential solutions:
api              | - Is MikroOrmModule a valid NestJS module?
api              | - If postgres_EntityManager is a provider, is it part of the current MikroOrmModule?
api              | - If postgres_EntityManager is exported from a separate @Module, is that module imported within MikroOrmModule?
api              |   @Module({
api              |     imports: [ /* the Module containing postgres_EntityManager */ ]
api              |   })
api              | 
api              |     at Injector.lookupComponentInParentModules (/app/node_modules/@nestjs/core/injector/injector.js:247:19)
api              |     at Injector.resolveComponentInstance (/app/node_modules/@nestjs/core/injector/injector.js:200:33)
api              |     at resolveParam (/app/node_modules/@nestjs/core/injector/injector.js:120:38)
api              |     at async Promise.all (index 0)
api              |     at Injector.resolveConstructorParams (/app/node_modules/@nestjs/core/injector/injector.js:135:27)
api              |     at Injector.loadInstance (/app/node_modules/@nestjs/core/injector/injector.js:61:13)
api              |     at Injector.loadProvider (/app/node_modules/@nestjs/core/injector/injector.js:88:9)
api              |     at /app/node_modules/@nestjs/core/injector/instance-loader.js:49:13
api              |     at async Promise.all (index 3)
api              |     at InstanceLoader.createInstancesOfProviders (/app/node_modules/@nestjs/core/injector/instance-loader.js:48:9)

```

**To Reproduce**
1. Create nest app, generate user module, define any user entity for Mikro-orm
2. Follow README.md to have multi-db setup with MikroOrmModule.forRootAsync, custom Repository or otherwise.
3. Hit bug in the user.module.ts file when trying to use UserRepository_<contextName>

**Expected behavior**
Requirement to be able to use the UserRepository in my service or any CustomRepository otherwise I have to move away from mikro-orm.

**Additional context**
/user/user.module.ts
```
import { Module } from '@nestjs/common';
import { MikroOrmModule } from '@mikro-orm/nestjs';

import { UserController } from './user.controller';
import { UserService } from './user.service';
import { User } from './user.entity.postgres';

@Module({
  imports: [MikroOrmModule.forFeature([User], 'postgres')],
  controllers: [UserController],
  providers: [UserService],
})
export class UserModule { }
```

/user/user.service.ts
```
import { EntityRepository } from '@mikro-orm/core';
import { InjectRepository } from '@mikro-orm/nestjs';
import { Injectable } from '@nestjs/common';

import { User } from './user.entity.postgres';

@Injectable()
export class UserService {
  constructor(
    @InjectRepository(User, 'postgres')
    private readonly userRepository: EntityRepository<User>,
  ) { }

  async findAll(): Promise<User[]> {
    return this.userRepository.findAll();
  }
}
```

/user/user.controller.ts
```
import { Controller, Get } from '@nestjs/common';

import { UserService } from './user.service';

@Controller('user')
export class UserController {
  constructor(private readonly userService: UserService) { }

  @Get()
  async users(): Promise<any> {
    return this.userService.findAll();
  }
}
```

/user/user.entity.postgres.ts
```
import { IsEmail } from 'class-validator';
import crypto from 'crypto';
import { Entity, PrimaryKey, Property } from '@mikro-orm/core';
import { v4 as uuid } from 'uuid';

@Entity()
export class User {
  @PrimaryKey()
  uuid: string = uuid();

  @Property()
  first_name: string;

  @Property()
  last_name: string;

  @Property()
  @IsEmail()
  email: string;

  @Property({ hidden: true })
  password: string;

  constructor(
    first_name: string,
    last_name: string,
    email: string,
    password: string,
  ) {
    this.first_name = first_name;
    this.last_name = last_name;
    this.email = email;
    this.password = crypto.createHmac('sha256', password).digest('hex');
  }
}
```

app.module.ts
```
import {
  Module,
  MiddlewareConsumer,
  NestModule,
  OnModuleInit,
} from '@nestjs/common';
import { MikroORM } from '@mikro-orm/core';
import { MikroOrmModule, MikroOrmMiddleware } from '@mikro-orm/nestjs';
import { ConfigModule, ConfigService } from '@nestjs/config';

import { join } from 'path';

import { AppController } from './app.controller';
import { AppService } from './app.service';
import { UserModule } from './user/user.module';

@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
    }),
    MikroOrmModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: (configService: ConfigService) => ({
        contextName: 'postgres',
        registerRequestContext: false,
        dbName: configService.get('POSTGRES_DB'),
        user: configService.get('POSTGRES_USERNAME'),
        password: configService.get('POSTGRES_PASSWORD'),
        host: configService.get('POSTGRES_HOST'),
        port: configService.get('POSTGRES_PORT'),
        type: 'postgresql',
        baseDir: __dirname,
        entities: [__dirname + 'dist/**/*.entity.postgres.ts'],
        entitiesTs: [__dirname + 'src/**/*.entity.postgres.ts'],
        migrations: {
          path: join(__dirname, 'migrations', 'postgres'),
          pattern: /^[\w-]+\d+\.ts$/,
          transactional: true,
          allOrNothing: true,
          emit: 'ts',
          tableName: 'mikro_orm_migrations',
        },
        autoLoadEntities: true,
      }),
    }),
    MikroOrmModule.forMiddleware(),
    UserModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule implements NestModule, OnModuleInit {
  constructor(private readonly orm: MikroORM) { }

  async onModuleInit(): Promise<void> {
    await this.orm.getMigrator().up();
  }

  configure(consumer: MiddlewareConsumer) {
    consumer.apply(MikroOrmMiddleware).forRoutes('*');
  }
}
```

**Versions**
| Dependency | Version |
| - | - |
| node | 19.5.0 |
| typescript | 4.9.5 |
| mikro-orm | 5.6.13 |
| @mikro-orm/postgresql | 5.6.13|

**Comment by occhiojoe** [comment]
Had some time tonight to revisit this, remade configs to use more standards found in docs.  Also then made two configs in the `src` folder for each DB.   Will have to explore other config options in the future.  Posting for anyone reading.

No issues anymore, closing post!

app.module.ts excerpt
```
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
    }),
    MikroOrmModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: (configService: ConfigService) => ({
        dbName: configService.get('POSTGRES_DB'),
        user: configService.get('POSTGRES_USERNAME'),
        password: configService.get('POSTGRES_PASSWORD'),
        host: configService.get('POSTGRES_HOST'),
        port: configService.get('POSTGRES_PORT'),
        type: 'postgresql',
        loadStrategy: LoadStrategy.JOINED,
        entities: ['dist/entities/postgres/*.entity.js'],
        entitiesTs: ['src/entities/postgres/*.entity.ts'],
        metadataProvider: TsMorphMetadataProvider,
      }),
    }),
    MikroOrmModule.forRootAsync({
      contextName: 'mongodb',
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: (configService: ConfigService) => ({
        dbName: configService.get('MONGODB_DB'),
        user: configService.get('MONGODB_USERNAME'),
        password: configService.get('MONGODB_PASSWORD'),
        clientUrl: configService.get('MONGODB_URL'),
        port: configService.get('MONGODB_PORT'),
        type: 'mongo',
        ensureIndexes: true,
        loadStrategy: LoadStrategy.JOINED,
        entities: ['dist/entities/mongodb/*.entity.js'],
        entitiesTs: ['src/entities/mongodb/*.entity.ts'],
        metadataProvider: TsMorphMetadataProvider,
      }),
    }),
```

src/mikro-orm.postgres.config.ts
```
import { defineConfig, LoadStrategy } from '@mikro-orm/core';
import { ConfigService } from '@nestjs/config';
import { TsMorphMetadataProvider } from '@mikro-orm/reflection';

import { join } from 'path';

const configService = new ConfigService();

export default defineConfig({
  dbName: configService.get('POSTGRES_DB'),
  user: configService.get('POSTGRES_USERNAME'),
  password: configService.get('POSTGRES_PASSWORD'),
  host: configService.get('POSTGRES_HOST'),
  port: configService.get('POSTGRES_PORT'),
  type: 'postgresql',
  loadStrategy: LoadStrategy.JOINED,
  entities: ['dist/entities/postgres/*.entity.js'],
  entitiesTs: ['src/entities/postgres/*.entity.ts'],
  migrations: {
    path: join(__dirname, 'migrations', 'postgres'),
  },
  seeder: {
    path: join(__dirname, 'seeder', 'postgres'),
  },
  metadataProvider: TsMorphMetadataProvider,
});
```

src/mikro-orm.mongodb.config.ts
```
import { defineConfig, LoadStrategy } from '@mikro-orm/core';
import { ConfigService } from '@nestjs/config';
import { TsMorphMetadataProvider } from '@mikro-orm/reflection';

import { join } from 'path';

const configService = new ConfigService();

export default defineConfig({
  dbName: configService.get('POSTGRES_DB'),
  user: configService.get('POSTGRES_USERNAME'),
  password: configService.get('POSTGRES_PASSWORD'),
  host: configService.get('POSTGRES_HOST'),
  port: configService.get('POSTGRES_PORT'),
  type: 'postgresql',
  loadStrategy: LoadStrategy.JOINED,
  entities: ['dist/entities/postgres/*.entity.js'],
  entitiesTs: ['src/entities/postgres/*.entity.ts'],
  migrations: {
    path: join(__dirname, 'migrations', 'postgres'),
  },
  seeder: {
    path: join(__dirname, 'seeder', 'postgres'),
  },
  metadataProvider: TsMorphMetadataProvider,
});
```

and added the "mikro-orm" key to my package.json
```
  "mikro-orm": {
    "useTsNode": true,
    "configPaths": [
      "./src/mikro-orm.postgres.config.ts",
      "./dist/mikro-orm.postgres.config.js",
      "./src/mikro-orm.mongodb.config.ts",
      "./dist/mikro-orm.mongodb.config.js"
    ]
  }
```
