### ISSUE TITLE
onApplicationShutdown throwing when we provide `connect: false` to mikroorm options

### ISSUE THREAD

**Issue by rhyek** [mikro-orm/nestjs#121]
**Describe the bug**
Writing unit tests for an nestjs 7.6 app where I can't replace modules, and am setting `connect: false` via config to mikro. On the `afterEach` hook I do `app.close()`, but I get the stack trace below.

**Stack trace**
```
    TypeError: Cannot read properties of undefined (reading 'destroy')

      at MySqlConnection.close (../node_modules/.pnpm/@mikro-orm+knex@5.3.1_@mikro-orm+core@5.3.1_@mikro-orm+entity-generator@5.3.1_@mikro-orm+migrations@5.3.1_mysql2@2.3.3/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:22:27)
          at async Promise.all (index 0)
      at MySqlDriver.close (../node_modules/.pnpm/@mikro-orm+core@5.3.1_@mikro-orm+entity-generator@5.3.1_@mikro-orm+migrations@5.3.1_@mikro-orm+mysql@5.3.1/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:61:9)
```

**Expected behavior**
nestjs mikro should maybe check for the `connect` option [here](https://github.com/mikro-orm/nestjs/blob/5501f45fb2270680614c6309b5272e8c35fe0450/src/mikro-orm-core.module.ts#L112).

**Additional context**
If I remove the `app.close()` my tests pass.

**Versions**

| Dependency | Version |
| - | - |
| node | v18.14.2 |
| typescript | 4.9 |
| mikro-orm | 5.3.1 |
| your-driver | mysql |

**Comment by B4nan** [comment]
This is already resolved in v6
