### ISSUE TITLE
Inject repository issue 

### ISSUE THREAD

**Issue by emulienfou** [mikro-orm/nestjs#125]
**Describe the bug**
When injecting entity repository it generate some issues.  
Either I have the error message: `Nest can't resolve dependencies of the Controller (EntityManager, UserRepository, ?). Please make sure that the argument UserRepository at index [2] is available in the AppModule context.`   
Or my repository have undefined values: `UserRepository { _em: undefined, entityName: undefined }`

**Stack trace**
```
[Nest] 682581  - 06/22/2023, 10:03:38 AM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the UserController (EntityManager, UserRepository, ?). Please make sure that the argument UserRepository at index [2] is available in the AppModule context.

Potential solutions:
- Is AppModule a valid NestJS module?
- If UserRepository is a provider, is it part of the current AppModule?
- If UserRepository is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing UserRepository */ ]
  })

Error: Nest can't resolve dependencies of the UserController (EntityManager, UserRepository, ?). Please make sure that the argument UserRepository at index [2] is available in the AppModule context.

Potential solutions:
- Is AppModule a valid NestJS module?
- If UserRepository is a provider, is it part of the current AppModule?
- If UserRepository is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing UserRepository */ ]
  })

```

**To Reproduce**
1. Create a simple entity:
```
@Entity({ tableName: "User", repository: () => UserRepository })
export class User {
  [EntityRepositoryType]?: UserRepository;
}
```
2. Create a simple repository
```
export class UserRepository extends EntityRepository<User> {}
```
3. Register MokroOrm module:
```
@Module({
  imports: [
    MikroOrmModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: (configService: ConfigService) => ({
        baseDir: __dirname,
        type: "postgresql",
        entities: [
          User,
        ],
      }),
    }),
  ],
})
```
4. Create a controller an inject EntityManager and Repository:
```
@Controller("/users")
export class UserController {
  constructor(
    private readonly em: EntityManager,
    private readonly userRepository: UserRepository,
    @InjectRepository(User)
    private readonly userRepository2: EntityRepository<User>
  ) {}

  @Get("/count")
  public async count(): Promise<number> {
    console.log(this.userRepository);
    console.log(this.userRepository2);
    console.log(this.em.getRepository(User));
    return this.em.getRepository(User).count();
  }
}
```

**Output**
1. Using the code ` @InjectRepository(User)
    private readonly userRepository2: EntityRepository<User>` will return the next error:
`Nest can't resolve dependencies of the UserController (EntityManager, UserRepository, ?). Please make sure that the argument UserRepository at index [2] is available in the AppModule context.`
2. `console.log(this.userRepository);` will return:   
`UserRepository { _em: undefined, entityName: undefined }`
3. `console.log(this.em.getRepository(User));` Will return:   
`UserRepository { _em: [EntityManager<32>], entityName: 'User' }`

**Expected behavior**
Expecting to inject entity repository without any issues.

**Versions**

| Dependency | Version |
| - | - |
| node | 18.16.0 |
| typescript | 4.9.5 |
| mikro-orm | 5.7.12 |
| mikro-orm/nestjs | 5.1.8 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
Please provide complete repro, those issues are very often about wrong imports or similar small details.

**Comment by emulienfou** [comment]
Hi @B4nan sorry for the delayed,
here my use-case and what I tested I have other issues with the CLI if I run the command `yarn mikro-orm migration:create --dump
`:

1. If I used the decorator `@InjectRepository` like so:
```ts
import { InjectRepository } from '@mikro-orm/nestjs';
import { EntityRepository } from '@mikro-orm/postgresql';
import { Injectable } from '@nestjs/common';
import { Company } from './company.entity';

@Injectable()
export class CompaniesService {
  constructor(
    @InjectRepository(Company)
    private readonly companyRepository: EntityRepository<Company>
  ) {}
}
```
I got this error:
```
TypeError: Cannot read properties of undefined (reading 'name')
    at Function.className (/home/david/WebstormProjects/nestjsx-crud/node_modules/@mikro-orm/core/utils/Utils.js:546:28)
    at getRepositoryToken (/home/david/WebstormProjects/nestjsx-crud/node_modules/@mikro-orm/nestjs/mikro-orm.common.js:20:28)
    at InjectRepository (/home/david/WebstormProjects/nestjsx-crud/node_modules/@mikro-orm/nestjs/mikro-orm.common.js:23:96)
    at Object.<anonymous> (/home/david/WebstormProjects/nestjsx-crud/integration/crud-mikro-orm/companies/companies.service.ts:16:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module.m._compile (/home/david/WebstormProjects/nestjsx-crud/node_modules/ts-node/src/index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/home/david/WebstormProjects/nestjsx-crud/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
```
2. If I use the entity manager directly, no error:
```ts
import { EntityManager } from '@mikro-orm/core';
import { EntityRepository } from '@mikro-orm/postgresql';
import { Injectable } from '@nestjs/common';
import { Company } from './company.entity';

@Injectable()
export class CompaniesService {
  constructor(readonly em: EntityManager) {
    const companyrepository = em.getRepository(Company);
  }
}
```

Here is my CompanyModule also:
```ts
import { MikroOrmModule } from '@mikro-orm/nestjs';
import { Module } from '@nestjs/common';
import { Company } from './company.entity';
import { CompaniesService } from './companies.service';
import { CompaniesController } from './companies.controller';

@Module({
  imports: [MikroOrmModule.forFeature([Company])],
  providers: [CompaniesService],
  exports: [CompaniesService],
  controllers: [CompaniesController],
})
export class CompaniesModule {}
```

And the result of the command: `yarn mikro-orm debug`:
```
Current MikroORM CLI configuration
 - dependencies:
   - mikro-orm 5.9.4
   - node 18.17.1
   - knex 2.5.1
   - pg 8.7.3
   - typescript 4.6.3
 - package.json found
 - ts-node enabled
 - searched config paths:
   - /home/david/WebstormProjects/nestjsx-crud/integration/crud-mikro-orm/mikro-orm.config.ts (found)
   - /home/david/WebstormProjects/nestjsx-crud/src/mikro-orm.config.ts (not found)
   - /home/david/WebstormProjects/nestjsx-crud/mikro-orm.config.ts (not found)
   - /home/david/WebstormProjects/nestjsx-crud/src/mikro-orm.config.js (not found)
   - /home/david/WebstormProjects/nestjsx-crud/mikro-orm.config.js (not found)
 - configuration found
 - database connection succesful
 - will use `entities` array (contains 0 references and 1 paths)
   - /home/david/WebstormProjects/nestjsx-crud/integration/crud-mikro-orm/**/*.entity{.ts,.js} (found)
```

**Comment by B4nan** [comment]
the first error means you have an import cycle and the class is resolved to `undefined` by the time it gets used. this is not fixable from the ORM point of view, it's a limitation of how circular imports work in combination with how decorators work (they are evaluated on require time). you need to restructure your code so this cannot happen.

one way around this is using string name instead of class reference:

```ts
@InjectRepository('Company') // string name here
private readonly companyRepository: EntityRepository<Company> // on type level its fine
```

**Comment by emulienfou** [comment]
Thanks for your help, was able to fix my issue
