### ISSUE TITLE
Cannot get `@UseRequestContext` to work in a REQUEST scoped BullMQ processor

### ISSUE THREAD

**Issue by tolgap** [mikro-orm/nestjs#142]
**Describe the bug**
Cannot get `@UseRequestContext` to work in a `Scope.REQUEST` scoped BullMQ processor

**Stack trace**
```
ValidationError: Using global EntityManager instance methods for context specific actions is disallowed. If you need to work with the global instance's identity map, use `allowGlobalContext` configuration option or `fork()` instead.
    at Function.cannotUseGlobalContext (/src/node_modules/@mikro-orm/core/errors.js:95:16)
    at SqlEntityManager.getContext (/src/node_modules/@mikro-orm/core/EntityManager.js:1217:44)
    at SqlEntityManager.findOne (/src/node_modules/@mikro-orm/core/EntityManager.js:337:25)
    at SqlEntityManager.findOneOrFail (/src/node_modules/@mikro-orm/core/EntityManager.js:400:33)
    at UserRepository.findOneOrFail (/src/node_modules/@mikro-orm/core/entity/EntityRepository.js:50:40)
    at InstanceWrapper.useFactory [as metatype] (/src/dist/apps/authentication/webpack:/libs/shopify-context/src/lib/shopify-context.providers.ts:24:14)
    at Injector.instantiateClass (/src/node_modules/@nestjs/core/injector/injector.js:368:55)
    at callback (/src/node_modules/@nestjs/core/injector/injector.js:65:45)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**To Reproduce**

Given a processor:

```ts
@Processor({
  name: 'test',
  scope: Scope.REQUEST,
})
export class TestProcessor extends WorkerHost {
  constructor(private readonly orm: MikroORM) {}
  
  async process(job: Job) {
    await this.handleJob(job.data);
  }

  @UseRequestContext()
  private async handleJob(data: any) {
    const userRepo = this.orm.em.getRepository(User)
    
    await userRepo.findOne({ id: data.userId });
  }
}
```

Does not work. It throws the Global entity manager error.

**If I remove the `scope: Scope.REQUEST` from the `@Processor`, it _does_ work.**

**Expected behavior**
I would expect the entity manager to be forked because its marked as `@UseRequestContext()`.

**Additional context**

Additionally, I also tried it with `@EnsureRequestContext` from v6, but same error there.

**Versions**

| Dependency | Version |
| - | - |
| node | 18.17 |
| typescript | 4.9.5 |
| mikro-orm | 5.8.1 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
Why would you combine those two approaches?

**Comment by tolgap** [comment]
> Why would you combine those two approaches?
It's simple really. One of the dependencies of my processor is request scoped.

> Also why dont you inject the entity manager directly?
What difference is that going to make? I need a `this.orm` to be available to make `@UseRequestContext` work.

**Comment by B4nan** [comment]
Because unlike the ORM class, the EM dependency will respect the request scope (probably).

**Comment by tolgap** [comment]
@B4nan your suggestions actually made me realize my mistake. I was injecting something into my `Processor` that used the EntityManager in its provider. So I had to wrap that provider in a `@UseRequestContext`.

Sorry for the confusion. Thank you!
