### ISSUE TITLE
findByCursor method not working on sqlite

### ISSUE THREAD

**Issue by jays1204** [mikro-orm/nestjs#161]
**Describe the bug**
When I use sqlite by memory, findByCursor method don't work. 

**Stack trace**
```
[Nest] 84341  - 02/08/2024, 2:18:03 PM   ERROR [ExceptionsHandler] select count(*) as `count` from `test_entity` as `t0` - SQLITE_ERROR: no such table: test_entity
TableNotFoundException: select count(*) as `count` from `test_entity` as `t0` - SQLITE_ERROR: no such table: test_entity
    at SqliteExceptionConverter.convertException (/Users/jays/Project/test/sample-repo/node_modules/@mikro-orm/sqlite/SqliteExceptionConverter.js:29:20)
    at SqliteDriver.convertException (/Users/jays/Project/test/sample-repo/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:326:54)
    at /Users/jays/Project/test/sample-repo/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:330:24
    at SqlEntityManager.count (/Users/jays/Project/test/sample-repo/node_modules/@mikro-orm/core/EntityManager.js:1222:23)
    at async Promise.all (index 1)
    at SqlEntityManager.findAndCount (/Users/jays/Project/test/sample-repo/node_modules/@mikro-orm/core/EntityManager.js:380:35)
    at SqlEntityManager.findByCursor (/Users/jays/Project/test/sample-repo/node_modules/@mikro-orm/core/EntityManager.js:445:35)
    at AppService.getHello (/Users/jays/Project/test/sample-repo/src/app.service.ts:10:18)
    at /Users/jays/Project/test/sample-repo/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at /Users/jays/Project/test/sample-repo/node_modules/@nestjs/core/router/router-proxy.js:9:17

previous Error: select count(*) as `count` from `test_entity` as `t0` - SQLITE_ERROR: no such table: test_entity```

**To Reproduce**
Steps to reproduce the behavior:
1. git clone https://github.com/jays1204/sample-repo.git
2. npm install 
3. npm run start:dev
4. curl -X GET http://localhost:3000
Then you will receive 500 http error. and server throw error.

**Expected behavior**
findByCursor method works well on sqlite memory.

**Additional context**
In case of sqlite with file, It works. and mysql also works. sqlite with memory only don't work.

**Versions**

| Dependency | Version |
| - | - |
| node | v20.10.0 |
| typescript | 5.1.3 |
| mikro-orm | 6.1.0 |
| your-driver | sqlite |

**Comment by B4nan** [comment]
You need to create the schema

https://mikro-orm.io/docs/faq#how-can-i-synchronize-my-database-schema-with-the-entities
