### ISSUE TITLE
Invalid wildcard path for configuration with path-to-regexp v6 (Fastify v3)

### ISSUE THREAD

**Issue by quinnturner** [mikro-orm/nestjs#3]
**Describe the bug**

`path-to-regexp` [deprecated](https://github.com/pillarjs/path-to-regexp/blob/master/Readme.md#compatibility-with-express--4x) the usage of `*` for a wildcard route:

> No wildcard asterisk (\*) - use parameters instead ((.\*) or :splat*)

While using Fastify v3, which uses path-to-regexp v6, and setting `app.setGlobalPrefix('api');` the project doesn't run.

Changing `*` to `(.*)` worked locally for me, though I have not confirmed if that will work with `path-to-regexp` pre `v6`.

**Stack trace**
```
(node:29800) UnhandledPromiseRejectionWarning: TypeError: Unexpected MODIFIER at 13, expected END
    at mustConsume (/Users/quinn/Dev/project/Phoenix/node_modules/middie/node_modules/path-to-regexp/src/index.ts:157:11)
    at parse (/Users/quinn/Dev/project/node_modules/middie/node_modules/path-to-regexp/src/index.ts:228:5)
    at stringToRegexp (/Users/quinn/Dev/project/node_modules/middie/node_modules/path-to-regexp/src/index.ts:494:25)
    at pathToRegexp (/Users/quinn/Dev/project/node_modules/middie/node_modules/path-to-regexp/src/index.ts:616:10)
    at Object.use (/Users/quinn/Dev/project/node_modules/middie/engine.js:23:16)
    at Object.use (/Users/quinn/Dev/project/node_modules/middie/index.js:30:21)
    at /Users/quinn/Dev/project/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:127:27
    at MiddlewareModule.registerHandler (/Users/quinn/Dev/project/node_modules/@nestjs/core/middleware/middleware-module.js:138:9)
    at MiddlewareModule.bindHandler (/Users/quinn/Dev/project/node_modules/@nestjs/core/middleware/middleware-module.js:96:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**To Reproduce**
1. In main.ts, add a global prefix: `app.setGlobalPrefix('api');`
2. Initialize the app with `MikroOrmModule.forRoot()`

**Expected behavior**
Should properly set the global prefix and also initialize MikroOrm

**Versions**

| Dependency | Version |
| - | - |
| node | v14 |
| @mikro-orm/core | v4 (latest) |
| @mikro-orm/nestjs | v4 (latest) |
| @nestjs/core | v7.4.1 |

**Comment by B4nan** [comment]
hey there @quinnturner, looks like the fastify support is probably broken again, as per #31, do you know something changed again? is it working fine for you?

(repro is here https://github.com/proptex/nestjs-fastify-mikro-orm)

**Comment by quinnturner** [comment]
Unfortunately, I stopped working on the project that used this stack several months ago, so I don't think I can help much.
